import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-20 bg-white flex font-bold shadow-sm items-center">
          <div className="container px-16 text-slate-500">SportRecap</div>
        </header>
        <main className="container mx-auto pt-0">{children}</main>
      </body>
    </html>
  );
}
