import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-20 bg-white flex font-bold shadow-sm items-center">
          <div className="container text-slate-500">
            <span className="px-6">SportRecap</span>
          </div>
        </header>
        <main className="container mx-auto">{children}</main>
        <footer className="h-20 border-t mt-20 border-t-slate-200 flex items-center">
          <div className="container text-slate-500">SportRecap – 2024</div>
        </footer>
      </body>
    </html>
  );
}
